# Generated by Django 3.1.5 on 2021-03-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='summonername',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
