# Generated by Django 3.1.5 on 2021-03-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210317_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accountId',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='puuid',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
