# Generated by Django 3.1.5 on 2021-03-24 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.CharField(max_length=100, unique=True)),
                ('victory', models.BooleanField(null=True)),
                ('participant1', models.CharField(max_length=4, null=True)),
                ('participant2', models.CharField(max_length=4, null=True)),
                ('participant3', models.CharField(max_length=4, null=True)),
                ('patricipant4', models.CharField(max_length=4, null=True)),
                ('patricipant5', models.CharField(max_length=4, null=True)),
                ('participant6', models.CharField(max_length=4, null=True)),
                ('participant7', models.CharField(max_length=4, null=True)),
                ('participant8', models.CharField(max_length=4, null=True)),
                ('participant9', models.CharField(max_length=4, null=True)),
                ('participant10', models.CharField(max_length=4, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
