# Generated by Django 3.1.5 on 2021-03-25 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner', models.CharField(max_length=100, null=True)),
                ('championid', models.CharField(max_length=100, null=True)),
                ('championname', models.CharField(max_length=100, null=True)),
                ('championicon', models.CharField(max_length=100, null=True)),
                ('win', models.BooleanField(null=True)),
                ('lane', models.CharField(max_length=100, null=True)),
                ('team', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='userparticipant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pu', to='match.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='match.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p10', to='match.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='match.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p3', to='match.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p6', to='match.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p7', to='match.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p8', to='match.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p9', to='match.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='patricipant4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p4', to='match.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='patricipant5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p5', to='match.participant'),
        ),
    ]
