# Generated by Django 3.1.5 on 2021-03-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20210324_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='patricipant4',
            new_name='participant4',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='patricipant5',
            new_name='participant5',
        ),
    ]
