# Generated by Django 3.1.5 on 2021-03-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20210324_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
