# Generated by Django 3.1.5 on 2021-03-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_participant_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='win',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
