# Generated by Django 3.1.5 on 2021-03-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_match_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='assists',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='deaths',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='kills',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
