# Generated by Django 3.1.5 on 2021-03-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20210325_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='matchid',
            field=models.CharField(max_length=100),
        ),
    ]
